#define MDI1			ai_modules_ptr[0].di[0]
#define MDI1_SHORT		ai_modules_ptr[0].di_sc[0]
#define MDI1_BREAK		ai_modules_ptr[0].di_br[0]
#define MDI1_FAULT		ai_modules_ptr[0].di_fault[0]
#define MDI1_LINK		ai_modules_ptr[0].link_state
#define MDI2			ai_modules_ptr[0].di[1]
#define MDI2_SHORT		ai_modules_ptr[0].di_sc[1]
#define MDI2_BREAK		ai_modules_ptr[0].di_br[1]
#define MDI2_FAULT		ai_modules_ptr[0].di_fault[1]
#define MDI2_LINK		ai_modules_ptr[0].link_state
#define MDI3			ai_modules_ptr[0].di[2]
#define MDI3_SHORT		ai_modules_ptr[0].di_sc[2]
#define MDI3_BREAK		ai_modules_ptr[0].di_br[2]
#define MDI3_FAULT		ai_modules_ptr[0].di_fault[2]
#define MDI3_LINK		ai_modules_ptr[0].link_state
#define MDI4			ai_modules_ptr[0].di[3]
#define MDI4_SHORT		ai_modules_ptr[0].di_sc[3]
#define MDI4_BREAK		ai_modules_ptr[0].di_br[3]
#define MDI4_FAULT		ai_modules_ptr[0].di_fault[3]
#define MDI4_LINK		ai_modules_ptr[0].link_state
#define MDI5			ai_modules_ptr[0].di[4]
#define MDI5_SHORT		ai_modules_ptr[0].di_sc[4]
#define MDI5_BREAK		ai_modules_ptr[0].di_br[4]
#define MDI5_FAULT		ai_modules_ptr[0].di_fault[4]
#define MDI5_LINK		ai_modules_ptr[0].link_state
#define MDI6			ai_modules_ptr[0].di[5]
#define MDI6_SHORT		ai_modules_ptr[0].di_sc[5]
#define MDI6_BREAK		ai_modules_ptr[0].di_br[5]
#define MDI6_FAULT		ai_modules_ptr[0].di_fault[5]
#define MDI6_LINK		ai_modules_ptr[0].link_state
#define MDI7			ai_modules_ptr[0].di[6]
#define MDI7_SHORT		ai_modules_ptr[0].di_sc[6]
#define MDI7_BREAK		ai_modules_ptr[0].di_br[6]
#define MDI7_FAULT		ai_modules_ptr[0].di_fault[6]
#define MDI7_LINK		ai_modules_ptr[0].link_state
#define MDI8			ai_modules_ptr[0].di[7]
#define MDI8_SHORT		ai_modules_ptr[0].di_sc[7]
#define MDI8_BREAK		ai_modules_ptr[0].di_br[7]
#define MDI8_FAULT		ai_modules_ptr[0].di_fault[7]
#define MDI8_LINK		ai_modules_ptr[0].link_state
#define MDO1			do_modules_ptr[0].do_state[0]
#define MDO1_FAULT		do_modules_ptr[0].do_err[0]
#define MDO1_LINK		do_modules_ptr[0].link_state
#define MDO2			do_modules_ptr[0].do_state[1]
#define MDO2_FAULT		do_modules_ptr[0].do_err[1]
#define MDO2_LINK		do_modules_ptr[0].link_state
#define MDO3			do_modules_ptr[0].do_state[2]
#define MDO3_FAULT		do_modules_ptr[0].do_err[2]
#define MDO3_LINK		do_modules_ptr[0].link_state
#define MDO4			do_modules_ptr[0].do_state[3]
#define MDO4_FAULT		do_modules_ptr[0].do_err[3]
#define MDO4_LINK		do_modules_ptr[0].link_state
