/*
 * moddef.h
 *
 *  Created on: 2 но€б. 2020 г.
 *      Author: User
 */

#ifndef MODDEF_H_
#define MODDEF_H_

#define MAI1_RAW	ai_modules[0].raw_value[0]
#define MAI2_RAW	ai_modules[0].raw_value[1]
#define MAI3_RAW	ai_modules[0].raw_value[2]
#define MAI4_RAW	ai_modules[0].raw_value[3]
#define MAI5_RAW	ai_modules[0].raw_value[4]
#define MAI6_RAW	ai_modules[0].raw_value[5]
#define MAI7_RAW	ai_modules[0].raw_value[6]
#define MAI8_RAW	ai_modules[0].raw_value[7]
#define MAI9_RAW	ai_modules[1].raw_value[0]
#define MAI10_RAW	ai_modules[1].raw_value[1]
#define MAI11_RAW	ai_modules[1].raw_value[2]
#define MAI12_RAW	ai_modules[1].raw_value[3]
#define MAI13_RAW	ai_modules[1].raw_value[4]
#define MAI14_RAW	ai_modules[1].raw_value[5]
#define MAI15_RAW	ai_modules[1].raw_value[6]
#define MAI16_RAW	ai_modules[1].raw_value[7]

#define MAI1		ai_number[0].sens_value[0]
#define MAI2		ai_number[0].sens_value[1]
#define MAI3		ai_number[0].sens_value[2]
#define MAI4		ai_number[0].sens_value[3]
#define MAI5		ai_number[0].sens_value[4]
#define MAI6		ai_number[0].sens_value[5]
#define MAI7		ai_number[0].sens_value[6]
#define MAI8		ai_number[0].sens_value[7]
#define MAI9		ai_number[1].sens_value[0]
#define MAI10		ai_number[1].sens_value[1]
#define MAI11		ai_number[1].sens_value[2]
#define MAI12		ai_number[1].sens_value[3]
#define MAI13		ai_number[1].sens_value[4]
#define MAI14		ai_number[1].sens_value[5]
#define MAI15		ai_number[1].sens_value[6]
#define MAI16		ai_number[1].sens_value[7]

#define MAI1_OVER	ai_number[0].ai_over[0]
#define MAI2_OVER	ai_number[0].ai_over[1]
#define MAI3_OVER	ai_number[0].ai_over[2]
#define MAI4_OVER	ai_number[0].ai_over[3]
#define MAI5_OVER	ai_number[0].ai_over[4]
#define MAI6_OVER	ai_number[0].ai_over[5]
#define MAI7_OVER	ai_number[0].ai_over[6]
#define MAI8_OVER	ai_number[0].ai_over[7]
#define MAI9_OVER	ai_number[1].ai_over[0]
#define MAI10_OVER	ai_number[1].ai_over[1]
#define MAI11_OVER	ai_number[1].ai_over[2]
#define MAI12_OVER	ai_number[1].ai_over[3]
#define MAI13_OVER	ai_number[1].ai_over[4]
#define MAI14_OVER	ai_number[1].ai_over[5]
#define MAI15_OVER	ai_number[1].ai_over[6]
#define MAI16_OVER	ai_number[1].ai_over[7]

#define MAI1_UNDER	ai_number[0].ai_under[0]
#define MAI2_UNDER	ai_number[0].ai_under[1]
#define MAI3_UNDER	ai_number[0].ai_under[2]
#define MAI4_UNDER	ai_number[0].ai_under[3]
#define MAI5_UNDER	ai_number[0].ai_under[4]
#define MAI6_UNDER	ai_number[0].ai_under[5]
#define MAI7_UNDER	ai_number[0].ai_under[6]
#define MAI8_UNDER	ai_number[0].ai_under[7]
#define MAI9_UNDER	ai_number[1].ai_under[0]
#define MAI10_UNDER	ai_number[1].ai_under[1]
#define MAI11_UNDER	ai_number[1].ai_under[2]
#define MAI12_UNDER	ai_number[1].ai_under[3]
#define MAI13_UNDER	ai_number[1].ai_under[4]
#define MAI14_UNDER	ai_number[1].ai_under[5]
#define MAI15_UNDER	ai_number[1].ai_under[6]
#define MAI16_UNDER	ai_number[1].ai_under[7]

#define MAI1_ALARM	ai_number[0].ai_alarm[0]
#define MAI2_ALARM	ai_number[0].ai_alarm[1]
#define MAI3_ALARM	ai_number[0].ai_alarm[2]
#define MAI4_ALARM	ai_number[0].ai_alarm[3]
#define MAI5_ALARM	ai_number[0].ai_alarm[4]
#define MAI6_ALARM	ai_number[0].ai_alarm[5]
#define MAI7_ALARM	ai_number[0].ai_alarm[6]
#define MAI8_ALARM	ai_number[0].ai_alarm[7]
#define MAI9_ALARM	ai_number[1].ai_alarm[0]
#define MAI10_ALARM	ai_number[1].ai_alarm[1]
#define MAI11_ALARM	ai_number[1].ai_alarm[2]
#define MAI12_ALARM	ai_number[1].ai_alarm[3]
#define MAI13_ALARM	ai_number[1].ai_alarm[4]
#define MAI14_ALARM	ai_number[1].ai_alarm[5]
#define MAI15_ALARM	ai_number[1].ai_alarm[6]
#define MAI16_ALARM	ai_number[1].ai_alarm[7]

#define MDI1		ai_number[0].di[0]
#define MDI2		ai_number[0].di[1]
#define MDI3		ai_number[0].di[2]
#define MDI4		ai_number[0].di[3]
#define MDI5		ai_number[0].di[4]
#define MDI6		ai_number[0].di[5]
#define MDI7		ai_number[0].di[6]
#define MDI8		ai_number[0].di[7]
#define MDI9		ai_number[1].di[0]
#define MDI10		ai_number[1].di[1]
#define MDI11		ai_number[1].di[2]
#define MDI12		ai_number[1].di[3]
#define MDI13		ai_number[1].di[4]
#define MDI14		ai_number[1].di[5]
#define MDI15		ai_number[1].di[6]
#define MDI16		ai_number[1].di[7]

#define MDI1_SHORT	ai_number[0].di_sc[0]
#define MDI2_SHORT	ai_number[0].di_sc[1]
#define MDI3_SHORT	ai_number[0].di_sc[2]
#define MDI4_SHORT	ai_number[0].di_sc[3]
#define MDI5_SHORT	ai_number[0].di_sc[4]
#define MDI6_SHORT	ai_number[0].di_sc[5]
#define MDI7_SHORT	ai_number[0].di_sc[6]
#define MDI8_SHORT	ai_number[0].di_sc[7]
#define MDI9_SHORT	ai_number[1].di_sc[0]
#define MDI10_SHORT	ai_number[1].di_sc[1]
#define MDI11_SHORT	ai_number[1].di_sc[2]
#define MDI12_SHORT	ai_number[1].di_sc[3]
#define MDI13_SHORT	ai_number[1].di_sc[4]
#define MDI14_SHORT	ai_number[1].di_sc[5]
#define MDI15_SHORT	ai_number[1].di_sc[6]
#define MDI16_SHORT	ai_number[1].di_sc[7]

#define MDI1_BREAK	ai_number[0].di_br[0]
#define MDI2_BREAK	ai_number[0].di_br[1]
#define MDI3_BREAK	ai_number[0].di_br[2]
#define MDI4_BREAK	ai_number[0].di_br[3]
#define MDI5_BREAK	ai_number[0].di_br[4]
#define MDI6_BREAK	ai_number[0].di_br[5]
#define MDI7_BREAK	ai_number[0].di_br[6]
#define MDI8_BREAK	ai_number[0].di_br[7]
#define MDI9_BREAK	ai_number[1].di_br[0]
#define MDI10_BREAK	ai_number[1].di_br[1]
#define MDI11_BREAK	ai_number[1].di_br[2]
#define MDI12_BREAK	ai_number[1].di_br[3]
#define MDI13_BREAK	ai_number[1].di_br[4]
#define MDI14_BREAK	ai_number[1].di_br[5]
#define MDI15_BREAK	ai_number[1].di_br[6]
#define MDI16_BREAK	ai_number[1].di_br[7]

#define MDI1_FAULT	ai_number[0].di_fault[0]
#define MDI2_FAULT	ai_number[0].di_fault[1]
#define MDI3_FAULT	ai_number[0].di_fault[2]
#define MDI4_FAULT	ai_number[0].di_fault[3]
#define MDI5_FAULT	ai_number[0].di_fault[4]
#define MDI6_FAULT	ai_number[0].di_fault[5]
#define MDI7_FAULT	ai_number[0].di_fault[6]
#define MDI8_FAULT	ai_number[0].di_fault[7]
#define MDI9_FAULT	ai_number[1].di_fault[0]
#define MDI10_FAULT	ai_number[1].di_fault[1]
#define MDI11_FAULT	ai_number[1].di_fault[2]
#define MDI12_FAULT ai_number[1].di_fault[3]
#define MDI13_FAULT	ai_number[1].di_fault[4]
#define MDI14_FAULT	ai_number[1].di_fault[5]
#define MDI15_FAULT	ai_number[1].di_fault[6]
#define MDI16_FAULT	ai_number[1].di_fault[7]

#endif /* MODDEF_H_ */
